<menu class="main">
    <li><a href="/advert/backend-main/">Объявления</a></li>
    <li><a href="/user/backend-main/">Пользователи</a></li>
    <li><a href="/article/backend-main/">Статьи</a></li>
    <li><a href="/group/backend-main/">Административные группы</a></li>
    <li><a href="/module/backend-main/">Модули</a></li>
    <li><a href="/category/backend-main/">Категории</a></li>
    <li><a href="/user/backend-country-list/">Страны</a></li>
    <li><a href="/user/backend-region-list/">Регионы</a></li>
    <li><a href="/user/backend-city-list/">Города</a></li>
    <li><a href="/authorization/logout/?referer=/admin/">Выход из системы</a></li>
</menu>