<?php

use Krugozor\Framework\Http\Request;
use Krugozor\Framework\View;

/** @var View $this */

?>
<!DOCTYPE html>
<html lang="ru">
<head>

    <?php include($this->getRealTemplatePath('Local/MetaTags')); ?>

    <?= $this->compileCss([
        'local' => ['reset.css', 'tags.css', 'classes.css', 'structure.css'],
        'getpassword' => ['frontend-getpassword.css'],
    ]) ?>

    <?= $this->getJs('local', 'library/krugozor.js') ?>
    <?= $this->getJs('local', 'library/krugozor.forms.js') ?>
    <?= $this->getJs('local', 'library/krugozor.ajax.js') ?>

</head>
<body itemscope itemtype="https://schema.org/WebPage">

<?php include $this->getRealTemplatePath('Local/FrontendTop') ?>

<div id="<?= $this->getPageId() ?>" class="content">

    <?php include $this->getRealTemplatePath('Common/Notification') ?>

    <header>
        <h1>
            <?= $this->getLang()->get('title')->item(0) ?>
        </h1>
    </header>

    <form method="post" action="<?= $this->getRequest()->getCanonicalRequestUri()->getEscapeUriValue() ?>">
        <fieldset>
            <legend>Идентификация пользователя</legend>

            <div class="two_column">
                <div class="left_column">
                    <div class="left_column_content">
                        <p>Если Вы забыли свой логин или пароль, введите какие-либо одни ваши данные, которые Вы указали
                            при регистрации &mdash; логин или email-адрес и нажмите на кнопку &laquo;выслать код
                            подтверждения&raquo;. Если при регистрации в системе Вы указали свой email-адрес, то на него
                            придет письмо с уникальной ссылкой. Пройдя по этой ссылке, Вы подтвердите свою
                            принадлежность к
                            указанному аккаунту и новый пароль будет выслан на Ваш регистрационный почтовый ящик.</p>
                        <p>Письмо должно придти в течение одной минуты. Если письма не будет в папке &laquo;Входящие&raquo;
                            &mdash; проверьте папку &laquo;Спам&raquo;.</p>
                        <p>Если письма не будет даже в &laquo;Спаме&raquo;, воспользуйтесь <a href="/help/contact">обратной
                                связью</a>.</p>
                    </div>
                </div>
                <div class="right_column">
                    <div class="right_column_content">

                        <?php if ($this->getErrors()->get('common_error')): ?>
                            <div class="field_row_fake">
                                <div></div>
                                <div class="group">
                                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError(
                                        $this->getErrors()->get('common_error'), 'arrow_bottom'
                                    ) ?>
                                </div>
                            </div>
                        <?php endif; ?>

                        <div class="field_row">
                            <label class="compulsory" for="user_login">
                                Ваш логин:
                            </label>
                            <div class="group">
                                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                                    'user[login]',
                                    $this->getRequest()->getRequest('user.login', Request::SANITIZE_STRING),
                                    ['id' => 'user_login']
                                )->getHtml() ?>

                                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError(
                                    $this->getErrors()->get('user_login')
                                ) ?>
                            </div>
                        </div>

                        <div class="field_row_fake">
                            <div></div>
                            <div class="group">или</div>
                        </div>

                        <div class="field_row">
                            <label class="compulsory" for="user_email">
                                Ваш email:
                            </label>
                            <div class="group">
                                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputEmail(
                                    'user[email]',
                                    $this->getRequest()->getRequest('user.email', Request::SANITIZE_STRING),
                                    ['id' => 'user_email']
                                )->getHtml() ?>

                                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError(
                                    $this->getErrors()->get('user_email')
                                ) ?>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </fieldset>

        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSubmit(
            'submit',
            'Выслать код подтверждения',
            ['class' => 'big_button button_margin_auto']
        )->getHtml() ?>

    </form>

</div>

<?php include $this->getRealTemplatePath('Local/FrontendBottom') ?>

</body>
</html>