<?php

use Krugozor\Framework\View;

/** @var View $this */

?>
<!DOCTYPE html>
<html lang="ru">
<head>

    <?php include($this->getRealTemplatePath('Local/MetaTags')); ?>

    <?= $this->compileCss([
        'local' => ['reset.css', 'tags.css', 'classes.css', 'structure.css'],
    ]) ?>

</head>
<body itemscope itemtype="https://schema.org/WebPage">

<?php include $this->getRealTemplatePath('Local/FrontendTop') ?>

<div class="content">

    <?php include $this->getRealTemplatePath('Common/Notification') ?>

    <header>
        <h1><?= $this->getLang()->get('title')->item(0) ?></h1>
    </header>

    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError(
        $this->getErrors()->get('common_error'), ''
    ) ?>
</div>

<?php include $this->getRealTemplatePath('Local/FrontendBottom') ?>

</body>
</html>