<?php

use Krugozor\Cover\CoverArray;
use Krugozor\Framework\Helper\Form;
use Krugozor\Framework\Helper\SortLink;
use Krugozor\Framework\Http\Request;
use Krugozor\Framework\Module\Advert\Service\FrontendUserAdvertsListService;
use Krugozor\Framework\Module\Category\Helper\OptionsListWithOptgroup;
use Krugozor\Framework\View;

/** @var View $this */

$searchCategory = $this->getRequest()->getRequest('category', Request::SANITIZE_INT);
$searchKeyword = $this->getRequest()->getRequest('keyword', Request::SANITIZE_STRING_FULLTEXT);

/** @var FrontendUserAdvertsListService $advertsListService */
$advertsListService = $this->getStorage()->get('advertsListService');

$advertsListService
    ->getPagination()
    ->getHelper()
    ->setRequestUriParameter('field_name', $advertsListService->getAlias())
    ->setRequestUriParameter('sort_order', $advertsListService->getOrder())
    ->setRequestUriParameter('category', $searchCategory)
    ->setRequestUriParameter('keyword', $searchKeyword)
    ->setCssNormalLinkClass('navigation_normal_link')
    ->setCssActiveLinkClass('navigation_open_link');
$pagination = $advertsListService->getPagination();

/** @var CoverArray $userCategories */
$userCategories = $this->getStorage()->get('userCategories');

$sortLink = new SortLink();

?>
<!DOCTYPE html>
<html lang="ru">
<head>

    <?php include($this->getRealTemplatePath('Local/MetaTags')) ?>

    <?= $this->compileCss([
        'local' => ['reset.css', 'tags.css', 'classes.css', 'structure.css'],
        'advert' => ['_adverts-list.css', 'frontend-user-adverts-list.css'],
    ]) ?>

    <?= $this->getJs('local', 'library/krugozor.js') ?>
    <?= $this->getJs('local', 'library/krugozor.forms.js') ?>
    <?= $this->getJs('advert', '_adverts-list.js') ?>
    <?= $this->getJs('advert', 'frontend-category-list.js') ?>

</head>
<body itemscope itemtype="https://schema.org/WebPage">

<?php include $this->getRealTemplatePath('Local/FrontendTop') ?>

<div class="content">

    <?php include $this->getRealTemplatePath('Common/Notification') ?>

    <header>
        <h1>
            <a class="space_nowrap"
               href="/authorization/frontend-login/">
                <?= $this->getLang()->get('title')->item(0) ?></a>
            /
            <span class="space_nowrap"><?= $this->getLang()->get('title')->item(1) ?></span>
        </h1>
    </header>

    <div class="subblock filter">
        <div class="two_column">
            <div class="left_column">
                <div class="left_column_content">
                    <div class="bheader add_header_icon add_category_search_icon">Фильтр по моим объявлениям:</div>
                    <form method="get"
                          action="<?= $this->getRequest()->getCanonicalRequestUri()->getEscapeUriValue() ?>">
                        <div class="field_row">
                            <label for="input_category">Поиск:</label>
                            <div class="group">
                                <?php
                                $select = $this->getHelper(Form::class)->inputSelect(
                                    'category',
                                    $searchCategory,
                                    ['id' => 'input_category']
                                );
                                $select->addOption($this->getHelper(Form::class)->inputOption('', 'Категория'));
                                foreach ((new OptionsListWithOptgroup($userCategories))->getOptions() as $option):
                                    $select->addOption($option);
                                endforeach;
                                echo $select->getHtml();
                                ?><label for="input_keyword">Поиск по слову:</label><?=
                                $this->getHelper(Form::class)->inputText(
                                    'keyword',
                                    $searchKeyword,
                                    ['maxlength' => 50, 'id' => 'input_keyword']
                                )->getHtml() ?><input type="submit" value="Поиск"><input
                                        class="js_reset_button" type="reset" value="Сбросить">
                            </div>
                        </div>
                        <div class="field_row">
                            <label>Сортировать по:</label>
                            <div class="group">
                                <ul class="user_advert_order_menu">
                                    <li>
                                        <?php
                                        echo $sortLink
                                            ->setFieldName('id')
                                            ->setAnchor('ID')
                                            ->setUrl($this->getRequest()->getCanonicalRequestUri()->getEscapeUriValue())
                                            ->setIconSrc('/img/local/system/icon/')
                                            ->setCurrentFieldName($advertsListService->getAlias())
                                            ->setCurrentSortOrder($advertsListService->getOrder())
                                            ->setQueryStringFromArray([
                                                'sep' => $advertsListService->getPagination()->getCurrentSeparator(),
                                                'page' => $advertsListService->getPagination()->getCurrentPage(),
                                                'category' => $searchCategory,
                                                'keyword' => $searchKeyword
                                            ])
                                            ->getHtml();
                                        ?>
                                    </li>
                                    <li>
                                        <?php
                                        echo $sortLink
                                            ->setFieldName('header')
                                            ->setAnchor('Заголовку')
                                            ->getHtml();
                                        ?>
                                    </li>
                                    <li>
                                        <?php
                                        echo $sortLink
                                            ->setFieldName('price')
                                            ->setAnchor('Цене')
                                            ->getHtml();
                                        ?>
                                    </li>
                                    <li>
                                        <?php
                                        echo $sortLink
                                            ->setFieldName('active')
                                            ->setAnchor('Открытые/Закрытые')
                                            ->getHtml();
                                        ?>
                                    </li>
                                    <li>
                                        <?php
                                        echo $sortLink
                                            ->setFieldName('image')
                                            ->setAnchor('Кол-ву изображений')
                                            ->getHtml();
                                        ?>
                                    </li>
                                    <li>
                                        <?php
                                        echo $sortLink
                                            ->setFieldName('advert_create_date')
                                            ->setAnchor('Дате создания')
                                            ->getHtml();
                                        ?>
                                    </li>
                                    <li>
                                        <?php
                                        echo $sortLink
                                            ->setFieldName('advert_edit_date')
                                            ->setAnchor('Дате редактирования')
                                            ->getHtml();
                                        ?>
                                    </li>
                                    <li>
                                        <?php
                                        echo $sortLink
                                            ->setFieldName('balance')
                                            ->setAnchor('По остаткам')
                                            ->getHtml();
                                        ?>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div id="js_add_advert" class="right_column">
                <div data-country="<?php if ($this->getCurrentUser()->getCountry()): ?><?= $this->getCurrentUser()->getCountry() ?><?php endif; ?>"
                     data-region="<?php if ($this->getCurrentUser()->getRegion()): ?><?= $this->getCurrentUser()->getRegion() ?><?php endif; ?>"
                     data-city="<?php if ($this->getCurrentUser()->getCity()): ?><?= $this->getCurrentUser()->getCity() ?><?php endif; ?>"
                     data-category="" class="right_column_content">
                    <a href="/advert/frontend-edit-advert/">
                        <span class="with_decoration">
                            Подать новое объявление
                        </span>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <?php if ($advertsListService->getList()->count()): ?>
        <ul class="advert_list advert_list_shop_33 advert_list_shop_20">
            <?php
            $view = new View($this->getRealTemplatePath('Advert/AdvertsList'));
            $view->getStorage()->offsetSet('advertsList', $advertsListService->getList());
            $view->setCurrentUser($this->getCurrentUser());
            $view->getStorage()->offsetSet('isFrontendUserAdvertsListController', true);
            $view->run();
            echo $view->getOutput();
            ?>
        </ul>
    <?php else: ?>
        <p>Вы еще не создали ни одного объявления.</p>
        <p>Для создания объявления <a href="/advert/frontend-edit-advert/">пройдите по этой ссылке</a>.</p>
    <?php endif; ?>

    <?php include $this->getRealTemplatePath('Advert/FrontendNavigation'); ?>
</div>

<?php include $this->getRealTemplatePath('Local/FrontendBottom') ?>
<?php include $this->getRealTemplatePath('Prodamus/Popup') ?>

</body>
</html>