<?php

use Krugozor\Framework\View;

/* @var $this View */

?>
<!DOCTYPE html>
<html lang="ru">
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="robots" content="noindex, nofollow">
    <meta charset="utf-8">
    <meta name="referrer" content="unsafe-url">
    <?= $this->getLang()->get('title')->getHtml() ?>

    <?= $this->compileCss([
        'local' => ['reset.css', 'tags.css', 'classes.css', 'structure.css'],
    ]) ?>

</head>
<body>

<?php include $this->getRealTemplatePath('Local/FrontendTop') ?>

<div id="<?=$this->getPageId()?>" class="content">
    <?php include $this->getRealTemplatePath('Common/Notification') ?>
</div>

<?php include $this->getRealTemplatePath('Local/FrontendBottom') ?>

</body></html>