<?php

use Krugozor\Cover\CoverArray;
use Krugozor\Framework\Module\Advert\Service\FrontendAdvertsListService;
use Krugozor\Framework\Module\Category\Helper\Subcategories;
use Krugozor\Framework\Module\User\Cover\TerritoryList;
use Krugozor\Framework\Module\User\Model\AbstractTerritory;
use Krugozor\Framework\Registry;
use Krugozor\Framework\Statical\Strings;
use Krugozor\Framework\View;

/** @var View $this */

/** @var FrontendAdvertsListService $advertsListService */
$advertsListService = $this->getStorage()->get('advertsListService');

$advertsListService
    ->getPagination()
    ->getHelper()
    ->setCssNormalLinkClass('navigation_normal_link')
    ->setCssActiveLinkClass('navigation_open_link')
    ->setViewLastPageLabel(false);
$pagination = $advertsListService->getPagination();

/** @var TerritoryList $territoryList */
$territoryList = $this->getStorage()->get('territoryList');

$bread_crumbs_postfix_text = Strings::createMessageFromParams(
    $this->getLang()->get('content.in_city'), [
        'city' =>
            $territoryList->get('city')?->getNameRu2()
                ?: $territoryList->get('region')?->getNameRu2()
                ?: $territoryList->get('country')->getNameRu2(),
    ]
);

$this->getLang()->get('title')->replaceParams(0, [
    'city' =>
        $territoryList->get('city')?->getNameRu2()
            ?: $territoryList->get('region')?->getNameRu2()
            ?: $territoryList->get('country')->getNameRu2()
]);


// Для Яндекса, что бы не ругался на одинаковые title
if (($page = $pagination->getCurrentPage()) > 1) {
    $this->getLang()->get('title')->addPostfix(0, Strings::createMessageFromParams(
        $this->getLang()->get('content.page_number'), ['page' => $page]
    ));
}

/** @var CoverArray $categories */
$categories = $this->getStorage()->get('categories');

/** @var CoverArray $specialAdvertsList */
$specialAdvertsList = $this->getStorage()->get('specialAdvertsList');

$canonicalUrl = $this->getRequest()->getCanonicalRequestUri()->getSimpleUriValue(true);
$siteName = Registry::getInstance()->get('HOSTINFO.SITE_NAME');
$host = $this->getRequest()->getCanonicalRequestUri()->getHost();

?>
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">

    <?php if ($pagination->getCurrentPage() == 1): ?>
        <meta name="robots"
              content="<?php if ($advertsListService->getList()->count()): ?>index, follow, noarchive<?php else: ?>none<?php endif; ?>">
    <?php else: ?>
        <meta name='robots' content="noindex, follow, noarchive">
    <?php endif; ?>

    <meta charset="utf-8">
    <meta name="referrer" content="unsafe-url">
    <meta name="keywords"
          content="подать объявление<?= $bread_crumbs_postfix_text ?>, разместить объявление<?= $bread_crumbs_postfix_text ?>, объявления<?= $bread_crumbs_postfix_text ?>, доска объявлений<?= $bread_crumbs_postfix_text ?>">
    <meta name="description" content="<?= $this->getLang()->get('title')->item(0) ?>">
    <?= $this->getLang()->get('title')->getHtml() ?>

    <?= $this->getLang()->get('title')->getOgHtml() ?>
    <meta property="og:type" content="website">
    <meta property="og:locale" content="ru_RU">
    <meta property="og:url" content="<?= $canonicalUrl ?>">
    <meta property="og:description"
          content="<?= $this->getLang()->get('title')->item(0) ?>">
    <meta property="og:site_name" content="<?= $siteName ?>">
    <meta property="og:image"
          content="<?= $host ?>/img/local/snippet.jpg">
    <meta property="og:image:secure_url"
          content="<?= $host ?>/img/local/snippet.jpg">
    <meta property="og:image:width" content="800">
    <meta property="og:image:height" content="600">
    <meta property="og:image:type" content="image/jpeg">

    <link rel="canonical" href="<?= $canonicalUrl ?>">

    <link rel="icon" href="<?= $host ?>/favicon.ico">
    <link rel="apple-touch-icon" href="<?= $host ?>/apple-touch-icon.png">

    <link rel="preload" href="/fonts/local/HANDGOTN.woff2" as="font" type="font/woff2" crossorigin>

    <?= $this->compileCss([
        'local' => ['reset.css', 'tags.css', 'classes.css', 'structure.css', 'categories.css'],
        'advert' => ['_adverts-list.css'],
    ]) ?>

    <?= $this->getJs('local', 'library/krugozor.js') ?>
    <?= $this->getJs('local', 'library/krugozor.ajax.js') ?>
    <?= $this->getJs('local', 'library/krugozor.locations.js'); ?>
    <?= $this->getJs('advert', '_adverts-list.js') ?>

    <script>window.yaContextCb = window.yaContextCb || []</script>
    <script src="https://yandex.ru/ads/system/context.js" async></script>
</head>
<body itemscope itemtype="https://schema.org/WebPage">

<?php include $this->getRealTemplatePath('Local/FrontendTop') ?>

<div id="<?= $this->getPageId() ?>" class="content">

    <?php include $this->getRealTemplatePath('Common/Notification') ?>

    <header>
            <nav <?php if ($territoryList->count() > 1): ?>itemprop="breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList"<?php endif; ?>>
            <?php
            // Для того, чт бы страница с наименованием "Доска бесплатных объявлений России / Московской области"
            // была на сайте в единственном экземпляре (для SEO) - только на первой, канонической странице списка
            if ($pagination->getCurrentPage() == 1): ?>

                <?php $i = 0;
                /** @var AbstractTerritory $territory */
                foreach ($territoryList as $territory): $i++; ?>
                    <?php if ($i != 1): ?>/<?php endif; ?>
                    <?php if ($territoryList->count() > $i): ?>
                        <span itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                            <a itemprop="item" href="<?= $territory->getUrl() ?>/categories/"
                            ><span itemprop="name">Объявления в <?= $territory->getNameRu2() ?></span
                                ><meta itemprop="position" content="<?= $i ?>"></a>
                        </span>
                    <?php endif; ?>
                <?php endforeach; ?>

                <?php if ($i > 1): // необходимо использовать контейнер BreadcrumbList как минимум с двумя элементами ListItems - google docs ?>
                    <h1 itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                        <span itemprop="name">Доска бесплатных объявлений <?= $territoryList->getLastTerritory()->getNameRu3() ?></span>
                        <meta itemprop="position" content="<?= $i ?>">
                    </h1>
                <?php else: ?>
                    <h1>Доска бесплатных объявлений <?= $territoryList->getLastTerritory()->getNameRu3() ?></h1>
                <?php endif; ?>

            <?php else: ?>

                <?php $i = 0;
                /** @var AbstractTerritory $territory */
                foreach ($territoryList as $territory): $i++; ?>
                    <?php if ($i != 1): ?>/<?php endif; ?>
                    <?php if ($territoryList->count() > $i): ?>
                        <span itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                            <a itemprop="item" href="<?= $territory->getUrl() ?>/categories/"
                            ><span itemprop="name">Объявления в <?= $territory->getNameRu2() ?></span
                                ><meta itemprop="position" content="<?= $i ?>"></a>
                        </span>
                    <?php else: ?>
                        <?php if ($i > 1): // необходимо использовать контейнер BreadcrumbList как минимум с двумя элементами ListItems - google docs ?>
                            <h1 itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                                <span itemprop="name">Объявления <?= $territory->getNameRu() ?></span>
                                <meta itemprop="position" content="<?= $i ?>">
                            </h1>
                        <?php else: ?>
                            <h1>Объявления <?= $territory->getNameRu() ?></h1>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endforeach; ?>

            <?php endif; ?>

            <?php if ($territoryList->isCountry()): ?>
                / <span id="js_region_select_wrap"></span>
            <?php elseif ($territoryList->isRegion()): ?>
                / <span id="js_city_select_wrap"></span>
            <?php endif; ?>
        </nav>
    </header>

    <?php if ($advertsListService->getList()->count()): ?>

        <div class="two_column two_column_wrap">
            <div class="left_column">
                <div class="left_column_content">

                    <h5 class="bheader">
                        Последние добавленные на сайт
                        объявления<?php if ($bread_crumbs_postfix_text): ?> <?= $bread_crumbs_postfix_text ?><?php endif; ?>
                    </h5>

                    <ul class="advert_list advert_list_shop_33 advert_list_shop_25">
                        <?php
                        $view = new View($this->getRealTemplatePath('Advert/AdvertsList'));
                        $view->getStorage()->offsetSet('advertsList', $advertsListService->getList());
                        $view->setCurrentUser($this->getCurrentUser());
                        $view->getStorage()->offsetSet('isFrontendCategoryListController', true);
                        $view->run();
                        echo $view->getOutput();
                        ?>
                    </ul>
                </div>
            </div>


            <div class="right_column">
                <div class="right_column_content advert_list_special">

                    <?php if ($categories->count()): ?>
                        <nav class="subblock categories_list single">
                            <?= (new Subcategories($categories))
                                ->setCurrentTerritory($territoryList->getLastTerritory())
                                ->getHtml()
                            ?>
                        </nav>
                    <?php endif; ?>

                    <!-- Yandex.RTB R-A-6810960-1 -->
                    <div class="subblock" id="yandex_rtb_R-A-6810960-1"></div>
                    <script>
                        window.yaContextCb.push(() => {
                            Ya.Context.AdvManager.render({
                                "blockId": "R-A-6810960-1",
                                "renderTo": "yandex_rtb_R-A-6810960-1"
                            })
                        })
                    </script>

                    <?php if (0): ?>
                        <div class="bheader add_header_icon add_star_icon">Специальные предложения</div>
                        <ul class="advert_list advert_list_special">
                            <?php
                            $view = new View($this->getRealTemplatePath('Advert/AdvertsList'));
                            $view->getStorage()->offsetSet('advertsList', $specialAdvertsList);
                            $view->setCurrentUser($this->getCurrentUser());
                            $view->run();
                            echo $view->getOutput();
                            ?>
                        </ul>
                    <?php endif; ?>
                </div>
            </div>
        </div>

    <?php else: ?>
        <p>Объявлений не найдено. Вы можете <a href="/advert/frontend-edit-advert/">подать новое объявление</a>
            бесплатно и без регистрации.</p>
    <?php endif; ?>

    <?php include_once $this->getRealTemplatePath('Advert/FrontendNavigation'); ?>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        /* Взято и изменено на основе метода из library/krugozor.locations.js */
        var nextStepCallback = function (locationObj) {
            window.location.href = locationObj.SelectElement.value;
        };

        /* Взято и изменено на основе метода из library/krugozor.locations.js */
        var createCallback = function (location_id, place_id) {
            if (!location_id || !this.creator.LOCATION_TYPES[location_id]) {
                return false;
            }
            this.location_id = location_id;
            var _this = this;
            try {
                var ajax = new Krugozor.Ajax();
                ajax.setObserverState(function (ajx) {
                    _this._addOptionsToSelect(this.locations);
                }, true);
                ajax.get(
                    "/user/frontend-ajax-location-url/?id=" + place_id +
                    '&category=0&location=' + this.creator.LOCATION_TYPES[this.location_id]
                );
            } catch (e) {
                console.log(e);
            }
        };

        <?php if ($territoryList->isCountry()): ?>
        var select_region_attributes = {name: 'region'};
        Krugozor.Location._next_step = nextStepCallback;
        var selectRegionObj = Krugozor.Location.createLocation(select_region_attributes, 'уточнить регион');
        selectRegionObj.create = createCallback;
        document.getElementById('js_region_select_wrap').appendChild(selectRegionObj.SelectElement);
        selectRegionObj.create(2, <?=$territoryList->getLastTerritory()->getId()?>);

        selectRegionObj.SelectElement.addEventListener('focus', function (e) {
            window.overlay = Krugozor.Overlay.addOverlay(0.6, function () {
                overlay.removeOverlay();
            });
        });
        selectRegionObj.SelectElement.addEventListener('change', function (e) {
            window.overlay.removeOverlay();
        });
        <?php elseif ($territoryList->isRegion()): ?>
        var select_city_attributes = {name: 'city'};
        Krugozor.Location._next_step = nextStepCallback;
        var selectCityObj = Krugozor.Location.createLocation(select_city_attributes, 'уточнить город');
        selectCityObj.create = createCallback;
        document.getElementById('js_city_select_wrap').appendChild(selectCityObj.SelectElement);
        selectCityObj.create(3, <?=$territoryList->getLastTerritory()->getId()?>);

        selectCityObj.SelectElement.addEventListener('focus', function (e) {
            window.overlay = Krugozor.Overlay.addOverlay(0.6, function () {
                overlay.removeOverlay();
            });
        });
        selectCityObj.SelectElement.addEventListener('change', function (e) {
            window.overlay.removeOverlay();
        });
        <?php endif; ?>
    });
</script>

<?php include $this->getRealTemplatePath('Local/FrontendBottom') ?>
<?php include_once $this->getRealTemplatePath('Prodamus/Popup') ?>

</body>
</html>