<?php

use Krugozor\Framework\Helper\Form;
use Krugozor\Framework\Module\Advert\Model\Advert;
use Krugozor\Framework\Registry;
use Krugozor\Framework\Statical\Strings;
use Krugozor\Framework\View;

/** @var View $this */

$userModel = $this->getStorage()->get('userModel');

/** @var int $autologin */
$autologin = $this->getStorage()->get('autologin');

/** @var int $userAdvertsCount */
$userAdvertsCount = $this->getStorage()->get('userAdvertsCount');

/** @var int $ml_autologin */
$ml_autologin = $this->getStorage()->get('ml_autologin');

?>
<!DOCTYPE html>
<html lang="ru">
<head>

    <?php include($this->getRealTemplatePath('Local/MetaTags')); ?>

    <?= $this->compileCss([
        'local' => ['reset.css', 'tags.css', 'classes.css', 'structure.css'],
        'authorization' => ['frontend-login.css'],
    ]) ?>

    <?= $this->getJs('local', 'library/krugozor.js') ?>
    <?= $this->getJs('local', 'library/krugozor.forms.js') ?>
    <?= $this->getJs('local', 'library/krugozor.ajax.js') ?>
    <?= $this->getJs('authorization', 'login.js') ?>

</head>
<body itemscope itemtype="https://schema.org/WebPage">

<?php include $this->getRealTemplatePath('Local/FrontendTop') ?>

<div id="<?= $this->getPageId() ?>" class="content">

    <?php include $this->getRealTemplatePath('Common/Notification') ?>

    <header>
        <h1>Мой личный кабинет</h1>
    </header>

    <?php if (!$this->getCurrentUser()->isGuest()): ?>

        <div class="two_column login">
            <div class="left_column">
                <menu class="left_column_content common_menu">
                    <li class="add">
                        <a href="/advert/frontend-edit-advert/">Подать новое объявление</a>
                    </li>
                    <li class="list">
                        <a href="/advert/frontend-user-adverts-list/">Управлять моими объявлениями</a>
                    </li>
                    <li class="userinfo">
                        <a href="/user/frontend-edit/">Моя личная информация</a>
                    </li>
                    <li class="logout">
                        <a onclick="return confirm('Вы действительно хотите завершить работу с сайтом?')"
                           href="/authorization/logout/?referer=<?= $this->getRequest()->getRequestUri()->getUrlencodeUriValue(true) ?>">Выйти</a>
                    </li>
                </menu>
            </div>
            <div class="right_column">
                <div class="right_column_content">
                    <?php if ($userAdvertsCount >= Advert::MIN_ADVERTS_COUNT_FOR_SHOW_PROFILE):
                        $url = implode('/', ['/profile', $this->getCurrentUser()->getId(), '']);
                        ?>
                        <article>
                            <ul>
                                <li>
                                    <h2>Вам доступен ваш Публичный профиль</h2>
                                    <p>Уважаемый пользователь, поскольку количество ваших объявлений превысило
                                        необходимое количество, вам
                                        бесплатно доступен ваш Публичный профиль:</p>

                                    <p class="profile_link">
                                        <var>
                                            <a target="_blank"
                                                href="<?= Registry::getInstance()->get('HOSTINFO.HOST') . $url ?>">
                                                <?= Registry::getInstance()->get('HOSTINFO.HOST_AS_TEXT') . $url ?>
                                            </a>
                                        </var>
                                    </p>

                                </li>
                                <li>
                                    <h2>Для чего нужен Публичный профиль?</h2>
                                    <p>Публичный профиль - это аккомуляция всех ваших объявлений на одной странице.
                                        Прочите <a href="/help/b2b">эту страницу</a> для понимания приемущества владения
                                        публичным профилем.</p>
                                </li>
                            </ul>
                        </article>
                    <?php else: ?>
                        <article>
                            <ul>
                                <li>
                                    <h2>Вам пока не доступен ваш Публичный профиль</h2>
                                    <p>Уважаемый пользователь, поскольку количество ваших объявлений ещё не превысило
                                        необходимое количество (<?= Advert::MIN_ADVERTS_COUNT_FOR_SHOW_PROFILE ?>&nbsp;штук),
                                        вам пока <b>не доступен</b> ваш Публичный
                                        профиль.</p>
                                </li>
                                <li>
                                    <h2>Для чего нужен Публичный профиль?</h2>
                                    <p>Публичный профиль - это аккомуляция всех ваших объявлений по одному URL-адресу в
                                        публичном доступе.
                                        Прочите <a href="/help/b2b">эту страницу</a> для понимания приемущества владения
                                        публичным профилем.</p>
                                </li>
                            </ul>
                        </article>
                    <?php endif; ?>
                </div>
            </div>
        </div>

    <?php else: ?>

        <form name="auth_form" method="post"
              action="<?= $this->getRequest()->getRequestUri()->getEscapeUriValue() ?>">
            <fieldset>
                <legend>Авторизация</legend>

                <div class="two_column logout">
                    <div class="left_column">
                        <div class="left_column_content">
                            <?php if ($this->getErrors()->get('authorization')): ?>
                                <div class="field_row_fake">
                                    <div></div>
                                    <div class="group">
                                        <?= $this->getHelper(Form::class)->getFieldError(
                                            $this->getErrors()->get('authorization'), 'arrow_bottom'
                                        ) ?>
                                    </div>
                                </div>
                            <?php endif; ?>

                            <div class="field_row">
                                <label class="compulsory" for="user_login">
                                    <?= $this->getLang()->get('content.login') ?>:
                                </label>
                                <div class="group">
                                    <?= $this->getHelper(Form::class)->inputText(
                                        'user[login]',
                                        $userModel->getLogin(),
                                        ['maxlength' => 255, 'id' => 'user_login']
                                    )->getHtml() ?>
                                    <?= $this->getHelper(Form::class)->getFieldError(
                                        $this->getErrors()->get('login')
                                    ) ?>
                                </div>
                            </div>

                            <div class="field_row">
                                <label class="compulsory" for="user_password">
                                    <?= $this->getLang()->get('content.password') ?>:
                                </label>
                                <div class="group hide_show_pass_chars">
                                    <?= $this->getHelper(Form::class)->inputPassword(
                                        'user[password]',
                                        '',
                                        [
                                            'maxlength' => 255,
                                            'id' => 'user_password',
                                        ]
                                    )->getHtml() ?>
                                    <img title="Скрыть/показать пароль" src="/svg/local/icon-eye-close.svg">

                                    <?= $this->getHelper(Form::class)->getFieldError(
                                        $this->getErrors()->get('password')
                                    ) ?>
                                </div>
                            </div>

                            <div class="field_row">
                                <label id="for_autologin" for="autologin">
                                    <?= $this->getLang()->get('content.remember_password') ?>
                                </label>
                                <div class="group">
                                    <?= $this->getHelper(Form::class)->inputFullCheckbox(
                                        'autologin', 1, 0,
                                        $autologin,
                                        ['id' => 'autologin']
                                    ) ?>
                                    <div class="animate_field_description animate_field_description_remember_password">
                                        <div class="animate_field_content">
                                            <div class="description_before_fields">
                                                <p>Включать данную опцию следует лишь в том случае, когда Вы твёрдо
                                                    убеждены,
                                                    что к данному компьютеру нет доступа посторонних лиц,
                                                    способных несанкционированно изменить или удалить Ваши
                                                    данные.</p>
                                            </div>
                                        </div>
                                        <div class="triangle-right-border"></div>
                                        <div class="triangle-right"></div>
                                    </div>
                                    <div id="change_cookie_days" class="<?php if ($autologin): ?>show<?php endif; ?>">
                                        <?= Strings::createMessageFromParams(
                                            $this->getLang()->get('content.remember_password_description'),
                                            ['days' => $ml_autologin],
                                            false
                                        ) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="right_column">
                        <div class="right_column_content">
                            <ul class="pretty_list_style_type">
                                <li class="info">
                                    <p>Если Вы не зарегистрированы на сайте, то <a title="Регистрация"
                                                                                   href="/user/frontend-registration/">это
                                            можно
                                            сделать прямо сейчас</a>.</p>
                                </li>
                                <li class="info">
                                    <p>Если Вы забыли свой пароль, то воспользуйтесь
                                        <a title="Восстановить забытый пароль"
                                           href="/getpassword/frontend-getpassword/">системой
                                            восстановления пароля</a>.</p>
                                </li>
                                <li class="info">
                                    <p>Подавать объявления на сайт можно <a href="/advert/frontend-edit-advert/">без
                                            регистрации</a>.
                                    </p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </fieldset>

            <?= $this->getHelper(Form::class)->inputHidden(
                'ml_autologin',
                $ml_autologin,
                ['id' => 'ml_autologin']
            )->getHtml() ?>

            <?= $this->getHelper(Form::class)->inputSubmit(
                'submit',
                'Войти в личный кабинет',
                ['class' => 'big_button button_margin_auto']
            )->getHtml() ?>
        </form>

    <?php endif; ?>
</div>

<?php include $this->getRealTemplatePath('Local/FrontendBottom') ?>

</body>
</html>