<!DOCTYPE html>
<html lang="ru">
<head>

    <?php
    /** @var View $this */

    use Krugozor\Framework\Http\Request;
    use Krugozor\Framework\View;

    include ($this->getRealTemplatePath('Common/MetaTags'))
    ?>

    <?= $this->compileCss([
        'local' => ['reset.css', 'tags.css', 'classes.css', 'backend.css'],
    ]) ?>

</head>
<body>

<?php include $this->getRealTemplatePath('Common/Notification') ?>
<?php include $this->getRealTemplatePath('Local/BackendMenu') ?>

<form method="post" action="<?= $this->getRequest()->getRequestUri()->getEscapeUriValue() ?>">
    <table class="edit">
        <colgroup>
            <col>
            <col>
        </colgroup>
        <tr>
            <th colspan="2">
                <?php if ($this->region->getId()): ?>
                    Редактирование региона &laquo;<?= $this->getHelper('\Krugozor\Framework\Helper\Format')->hsc($this->region->getNameRu()) ?>&raquo;
                <?php else: ?>
                    Добавление региона
                <?php endif; ?>
            </th>
        </tr>
        <tr>
            <td><strong class="compulsory">Страна:</strong></td>
            <td><?php
                $select = $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSelect('region[id_country]', $this->region->getIdCountry());
                $select->addOption($this->getHelper('\Krugozor\Framework\Helper\Form')->inputOption(0, $this->getLang()->get('content.select_value')));
                foreach ($this->countryList as $country):
                    $select->addOption($this->getHelper('\Krugozor\Framework\Helper\Form')->inputOption($country->getId(), $country->getNameRu()));
                endforeach;
                echo $select->getHtml();
                ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->getErrors()->get('id_country')) ?></td>
        </tr>
        <tr>
            <td><strong class="compulsory">Вес:</strong></td>
            <td>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText('region[weight]', $this->region->getWeight(), array('maxlength' => 10))->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->getErrors()->get('weight')) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Важный регион:</strong></td>
            <td>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox('region[is_important_region]', 1, 0, $this->region->getIsImportantRegion()) ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->getErrors()->get('is_important_region')) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Имя региона RUS (в именительном падеже):</strong></td>
            <td>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText('region[name_ru]', $this->region->getNameRu(), array('maxlength' => 50))->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->getErrors()->get('name_ru')) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Имя региона RUS (в предложном падеже):</strong></td>
            <td>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText('region[name_ru2]', $this->region->getNameRu2(), array('maxlength' => 50))->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->getErrors()->get('name_ru2')) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Имя региона ENG:</strong></td>
            <td>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText('region[name_en]', $this->region->getNameEn(), array('maxlength' => 50))->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->getErrors()->get('name_en')) ?>
            </td>
        </tr>
        <tr >
            <td colspan="2">
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('region[id]', $this->region->getId())->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSubmit('submit', $this->getLang()->get('content.save_changes'))->getHtml() ?>
                &nbsp;&nbsp;&nbsp;
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox('return_on_page', 1, 0, $this->getRequest()->getRequest('return_on_page', Request::SANITIZE_INT), array('id' => 'label_return_on_page')) ?>
                &nbsp;<?= $this->getHelper('\Krugozor\Framework\Helper\Form')->label($this->getLang()->get('content.return_to_this_page'), 'label_return_on_page')->getHtml() ?>
            </td>
        </tr>
    </table>
</form>

<?php include $this->getRealTemplatePath('Common/DebugInfo') ?>

</body>
</html>