<!DOCTYPE html>
<html lang="ru">
<head>

    <?php
    /** @var View $this */

    use Krugozor\Framework\View;

    include ($this->getRealTemplatePath('Common/MetaTags'))
    ?>

    <?= $this->compileCss([
        'local' => ['reset.css', 'tags.css', 'classes.css', 'backend.css'],
        'user' => ['backend-country-list.css'],
    ]) ?>

</head>
<body>

<?php include $this->getRealTemplatePath('Common/Notification') ?>
<?php include $this->getRealTemplatePath('Local/BackendMenu') ?>

<table class="datatable">
    <?php if ($this->countryList->getList()->count()): ?>
        <colgroup>
            <col><col><col><col><col>
            <col><col><col><col>
        </colgroup>
        <tr>
            <th colspan="8">Список стран</th>
        </tr>
        <tr>
            <th>
                <?php
                $linker = $this->getHelper('\Krugozor\Framework\Helper\SortLink')
                    ->setFieldName('id')
                    ->setAnchor($this->getLang()->get('content.id'))
                    ->setUrl($this->getRequest()->getCanonicalRequestUri()->getSimpleUriValue())
                    ->setIconSrc('/img/local/system/icon/')
                    ->setCurrentFieldName($this->countryList->getAlias())
                    ->setCurrentSortOrder($this->countryList->getOrder())
                    ->setQueryStringFromArray(array(
                        'sep' => $this->countryList->getPagination()->getCurrentSeparator(),
                        'page' => $this->countryList->getPagination()->getCurrentPage(),
                    ));

                echo $linker->getHtml();
                ?>
            </th>
            <th>
                <?php
                echo $linker->setFieldName('active')
                    ->setAnchor('Активно')
                    ->getHtml(); ?>
            </th>
            <th>
                <?php
                echo $linker->setFieldName('weight')
                    ->setAnchor('Вес')
                    ->getHtml(); ?>
            </th>
            <th>
                <?php
                echo $linker->setFieldName('name_ru')
                    ->setAnchor('Страна RU')
                    ->getHtml(); ?>
            </th>
            <th>
                <?php
                echo $linker->setFieldName('name_ru2')
                    ->setAnchor('Страна RU')
                    ->getHtml(); ?>
            </th>
            <th>
                <?php
                echo $linker->setFieldName('name_en')
                    ->setAnchor('Страна EN')
                    ->getHtml(); ?>
            </th>
            <th colspan="4">
                <?= $this->getLang()->get('content.actions') ?>
            </th>
        </tr>

        <?php foreach ($this->countryList->getList() as $country): ?>
            <tr>
                <td id="country_<?= $country->getId() ?>"><?= $country->getId() ?></td>
                <td>
                    <?php if ($country->getActive()): ?>
                        <?= $this->getLang()->get('content.yes') ?>
                    <?php else: ?>
                        <span><?= $this->getLang()->get('content.no') ?></span>
                    <?php endif; ?>
                </td>
                <td><?= $country->getWeight() ?></td>
                <td>
                    <a href="/user/backend-region-list/?id_country=<?= $country->getId() ?>"><?= $this->getHelper('\Krugozor\Framework\Helper\Format')->run($country->getNameRu(), 'decode', 'hsc') ?></a>
                </td>
                <td><?= $this->getHelper('\Krugozor\Framework\Helper\Format')->run($country->getNameRu2(), 'decode', 'hsc') ?></td>
                <td><?= $this->getHelper('\Krugozor\Framework\Helper\Format')->run($country->getNameEn(), 'decode', 'hsc') ?></td>
                <td ><a
                            href="/user/backend-country-edit/?id=<?= $country->getId() ?>&amp;referer=<?= $this->getRequest()->getRequestUri()->getUrlencodeUriValue(true) ?>"><img
                                src="/img/local/system/icon/edit.png" alt=""></a></td>
                <td ><img src="/img/local/system/icon/delete_empty.png" alt=""></td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <th><h4>Список стран</h4></th>
        </tr>
        <tr>
            <td><?= $this->getLang()->get('content.not_found_request_data') ?></td>
        </tr>
    <?php endif; ?>
</table>

<?php
$pagination = $this->countryList->getPagination();
$pagination
    ->getHelper()
    ->setCssNormalLinkClass('navigation_normal_link')
    ->setCssActiveLinkClass('navigation_active_link')
    ->setRequestUriParameter('field_name', $this->countryList->getAlias())
    ->setRequestUriParameter('sort_order', $this->countryList->getOrder());
?>

<?php include $this->getRealTemplatePath('Common/Navigation') ?>

<?php include $this->getRealTemplatePath('Common/DebugInfo') ?>

</body>
</html>