<?php

use Krugozor\Framework\Helper\Form;
use Krugozor\Framework\Http\Request;
use Krugozor\Framework\Module\User\Model\User;
use Krugozor\Framework\Module\User\Type\UserType;
use Krugozor\Framework\Validator\StringLengthValidator;
use Krugozor\Framework\Validator\TelegramValidator;
use Krugozor\Framework\View;

/** @var View $this */

$captcha_code = $this->getStorage()->offsetGet('captcha_code');
$session_id = $this->getStorage()->offsetGet('session_id');
$session_name = $this->getStorage()->offsetGet('session_name');
$password_1 = $this->getStorage()->offsetGet('password_1');
$password_2 = $this->getStorage()->offsetGet('password_2');

/** @var User $user */
$user = $this->getStorage()->offsetGet('user');

?>
<!DOCTYPE html>
<html lang="ru">
<head>

    <?php include($this->getRealTemplatePath('Local/MetaTags')); ?>

    <?= $this->compileCss([
        'local' => ['reset.css', 'tags.css', 'classes.css', 'structure.css'],
        'user' => ['frontend-registration.css'],
    ]) ?>

    <?= $this->getJs('local', 'library/krugozor.js') ?>
    <?= $this->getJs('local', 'library/krugozor.forms.js') ?>
    <?= $this->getJs('local', 'library/krugozor.ajax.js') ?>
    <?= $this->getJs('local', 'library/krugozor.locations.js'); ?>
    <?= $this->getJs('local', 'phoneinput.js') ?>
    <?= $this->getJs() ?>

</head>
<body itemscope itemtype="https://schema.org/WebPage">

<?php include $this->getRealTemplatePath('Local/FrontendTop') ?>

<div id="<?= $this->getPageId() ?>" class="content">

    <?php include $this->getRealTemplatePath('Common/Notification') ?>

    <article class="two_column">
        <div class="left_column">
            <div class="left_column_content">
                <!-- left -->
                <header>
                    <h1><?= $this->getLang()->get('title')->item(0) ?></h1>
                </header>

                <form method="post"
                      action="<?= $this->getRequest()->getCanonicalRequestUri()->getEscapeUriValue() ?>">

                    <?= $this->getHelper(Form::class)->getFieldError(
                        $this->getErrors()->get('system_error')
                    ) ?>

                    <fieldset>
                        <legend>Регистрационная информация</legend>

                        <div class="field_row_fake">
                            <div></div>
                            <div class="group">
                                <div class="description_before_fields extended_without_icon extended extended_width_80">
                                    <p>Регистрационная информация заполняется только один раз.<br>В
                                        последующем Вы сможете подавать объявления на наш сайт без повторного
                                        указания этой
                                        информации.</p>
                                </div>
                            </div>
                        </div>

                        <div class="field_row">
                            <label class="compulsory" for="user_login">
                                Ваш будущий логин:
                            </label>
                            <div class="group">
                                <?= $this->getHelper(Form::class)->inputText(
                                    'user[login]',
                                    $user->getLogin(),
                                    [
                                        'maxlength' => StringLengthValidator::VARCHAR_MAX_LENGTH,
                                        'id' => 'user_login',
                                        'required' => 'required'
                                    ]
                                )->getHtml() ?>
                                <div class="animate_field_description">
                                    <div class="animate_field_content">
                                        <div class="description_before_fields">
                                            <p>Придумайте себе логин. Логин не то же, что и имя, а просто уникальный
                                                идентификатор,
                                                идентифицирующий Вас как участника. Допускается любая комбинация
                                                символов латинского
                                                алфавита (a—z), цифр (0—9), знака подчёркивания (_) или знака дефис
                                                (-).</p>
                                        </div>
                                    </div>
                                    <div class="triangle-right-border"></div>
                                    <div class="triangle-right"></div>
                                </div>
                                <?= $this->getHelper(Form::class)->getFieldError(
                                    $this->getErrors()->get('login')
                                ) ?>
                            </div>
                        </div>

                        <div class="field_row">
                            <label class="compulsory" for="user_password_1">
                                Ваш будущий пароль:
                            </label>
                            <div class="group hide_show_pass_chars">
                                <?= $this->getHelper(Form::class)->inputPassword(
                                    'user[password_1]',
                                    $password_1,
                                    [
                                        'maxlength' => StringLengthValidator::VARCHAR_MAX_LENGTH,
                                        'id' => 'user_password_1',
                                        'autocomplete' => 'off',
                                        'required' => 'required'
                                    ]
                                )->getHtml() ?>

                                <div class="animate_field_description">
                                    <div class="triangle-right-border"></div>
                                    <div class="triangle-right"></div>
                                    <div class="animate_field_content">
                                        <div class="description_before_fields">
                                            <p>Придумайте себе пароль. Допускается любая комбинация символов латинского
                                                алфавита (a—z),
                                                цифр (0—9), знака подчёркивания (_) или знака дефис (-).</p>
                                        </div>
                                    </div>
                                </div>

                                <img title="Скрыть/показать пароль" src="/svg/local/icon-eye-close.svg">

                                <?= $this->getHelper(Form::class)->getFieldError(
                                    $this->getErrors()->get('password_1')
                                ) ?>
                            </div>
                        </div>

                        <div class="field_row">
                            <label class="compulsory" for="user_password_2">
                                Повторите пароль:
                            </label>
                            <div class="group hide_show_pass_chars">
                                <?= $this->getHelper(Form::class)->inputPassword(
                                    'user[password_2]',
                                    $password_2,
                                    [
                                        'maxlength' => StringLengthValidator::VARCHAR_MAX_LENGTH,
                                        'id' => 'user_password_2',
                                        'autocomplete' => 'off',
                                        'required' => 'required'
                                    ]
                                )->getHtml() ?>

                                <div class="animate_field_description">
                                    <div class="triangle-right-border"></div>
                                    <div class="triangle-right"></div>
                                    <div class="animate_field_content">
                                        <div class="description_before_fields">
                                            <p>Повторите введённый выше пароль.</p>
                                        </div>
                                    </div>
                                </div>

                                <img title="Скрыть/показать пароль" src="/svg/local/icon-eye-close.svg">

                                <?= $this->getHelper(Form::class)->getFieldError(
                                    $this->getErrors()->get('password_2')
                                ) ?>

                                <?= $this->getHelper(Form::class)->getFieldError(
                                    $this->getErrors()->get('password')
                                ) ?>
                            </div>
                        </div>

                        <div class="field_row">
                            <label class="compulsory" for="user_captcha">
                                Введите цифры с изображения:
                            </label>
                            <div class="group captcha_block">
                                <div class="fields_wrap">
                                    <?= $this->getHelper(Form::class)->inputNumber(
                                        'captcha_code',
                                        $captcha_code,
                                        [
                                            'required' => 'required',
                                            'id' => 'captcha_code',
                                            'min' => 0,
                                            'max' => 9999,
                                        ]
                                    )->getHtml() ?><!--
                                    --><div
                                            class="animate_field_description animate_field_captcha">
                                        <div class="animate_field_content">
                                            <div class="description_before_fields">
                                                <p>Если вы не видите число на картинке, нажмите на картинку мышкой.</p>
                                            </div>
                                        </div>
                                        <div class="triangle-right-border"></div>
                                        <div class="triangle-right"></div>
                                    </div><!--
                        --><img data-src="/captcha/main/?session_name=<?= $session_name ?>&amp;session_id=<?= $session_id ?>"
                                onclick="this.src=this.getAttribute('data-src')+'&'+Math.random()" alt=""
                                title="Если вы не видите число на картинке, нажмите на картинку мышкой"
                                src="/captcha/main/?session_name=<?= $session_name ?>&amp;session_id=<?= $session_id ?>">
                                    <div class="description_before_fields extended_without_icon">
                                        Если вы не видите число на картинке, нажмите на картинку мышкой
                                    </div>
                                    <?= $this->getHelper(Form::class)->getFieldError(
                                        $this->getErrors()->get('captcha')
                                    ) ?>
                                </div>
                            </div>
                        </div>
                    </fieldset>

                    <fieldset>
                        <legend>Контактная информация</legend>
                        <div class="field_row_fake">
                            <div></div>
                            <div class="group">
                                <div class="description_before_fields extended_without_icon extended extended_width_80">
                                    <p>Поля ниже лучше заполнить сейчас, чтобы в каждом новом
                                        создаваемом Вами объявлении Ваши контактные данные подставлялись
                                        автоматически.</p>
                                </div>
                            </div>
                        </div>

                        <div class="field_row">
                            <label class="compulsory" for="user_email">
                                Email-адрес:
                            </label>
                            <div class="group">
                                <?= $this->getHelper(Form::class)->inputText(
                                    'user[email]',
                                    $user->getEmail()->getValue(),
                                    [
                                        'maxlength' => StringLengthValidator::VARCHAR_MAX_LENGTH,
                                        'id' => 'user_email',
                                        'required' => 'required'
                                    ]
                                )->getHtml() ?>

                                <div class="animate_field_description">
                                    <div class="animate_field_content">
                                        <div class="description_before_fields">
                                            <p>Указывайте реальный email-адрес, иначе в случае необходимости Вы не
                                                сможете восстановить забытый пароль.</p>
                                        </div>
                                    </div>
                                    <div class="triangle-right-border"></div>
                                    <div class="triangle-right"></div>
                                </div>

                                <?= $this->getHelper(Form::class)->getFieldError(
                                    $this->getErrors()->get('email')
                                ) ?>
                            </div>
                        </div>

                        <div class="field_row">
                            <label for="user_first_name">Ваше имя:</label>
                            <div class="group">
                                <?= $this->getHelper(Form::class)->inputText(
                                    'user[first_name]',
                                    $user->getFirstName(),
                                    [
                                        'maxlength' => 30,
                                        'id' => 'user_first_name'
                                    ]
                                )->getHtml() ?>

                                <?= $this->getHelper(Form::class)->getFieldError(
                                    $this->getErrors()->get('first_name')
                                ) ?>
                            </div>
                        </div>

                        <div class="field_row">
                            <label for="user_phone">Телефон:</label>
                            <div class="group">
                                <?= $this->getHelper(Form::class)->inputText(
                                    'user[phone]',
                                    $user->getPhone(),
                                    [
                                        'maxlength' => StringLengthValidator::VARCHAR_MAX_LENGTH,
                                        'id' => 'user_phone',
                                        'data-tel-input' => 'data-tel-input'
                                    ]
                                )->getHtml() ?>

                                <div class="animate_field_description">
                                    <div class="animate_field_content">
                                        <div class="description_before_fields">
                                            <p>Номер телефона в международном формате, пример: +7 (999) 111-22-33<br>
                                                Допустимые для ввода номера: Россия, Украина, Белоруссия, Казахстан.</p>
                                        </div>
                                    </div>
                                    <div class="triangle-right-border"></div>
                                    <div class="triangle-right"></div>
                                </div>

                                <?= $this->getHelper(Form::class)->getFieldError(
                                    $this->getErrors()->get('phone')
                                ) ?>
                            </div>
                        </div>

                        <div class="field_row">
                            <label for="user_telegram">Telegram (никнейм):</label>
                            <div class="group">
                                <?= $this->getHelper(Form::class)->inputText(
                                    'user[telegram]',
                                    $user->getTelegram(),
                                    [
                                        'id' => 'user_telegram',
                                        'maxlength' => TelegramValidator::MAX_LENGTH
                                    ]
                                )->getHtml() ?>

                                <?= $this->getHelper(Form::class)->getFieldError(
                                    $this->getErrors()->get('telegram')
                                ) ?>
                            </div>
                        </div>

                        <div class="field_row">
                            <label for="user_url">URL:</label>
                            <div class="group">
                                <?= $this->getHelper(Form::class)->inputUrl(
                                    'user[url]',
                                    $user->getUrl()->getValue(),
                                    [
                                        'maxlength' => StringLengthValidator::VARCHAR_MAX_LENGTH,
                                        'id' => 'user_url',
                                        'autocomplete' => 'on'
                                    ]
                                )->getHtml() ?>

                                <div class="animate_field_description">
                                    <div class="animate_field_content">
                                        <div class="description_before_fields">
                                            <p>Введите адрес начиная с http:// или https://</p>
                                        </div>
                                    </div>
                                    <div class="triangle-right-border"></div>
                                    <div class="triangle-right"></div>
                                </div>

                                <?= $this->getHelper(Form::class)->getFieldError(
                                    $this->getErrors()->get('url')
                                ) ?>
                            </div>
                        </div>

                        <div class="field_row">
                            <label for="user_skype">Skype:</label>
                            <div class="group">
                                <?= $this->getHelper(Form::class)->inputText(
                                    'user[skype]',
                                    $user->getSkype(),
                                    [
                                        'maxlength' => StringLengthValidator::MD5_MAX_LENGTH,
                                        'id' => 'user_skype'
                                    ]
                                )->getHtml() ?>

                                <?= $this->getHelper(Form::class)->getFieldError(
                                    $this->getErrors()->get('skype')
                                ) ?>
                            </div>
                        </div>

                        <div class="field_row">
                            <label>Место вашего проживания или территориальное расположение вашей
                                организации:</label>
                            <div class="group">
                                <div class="fields_wrap cities">
                                    <p>
                                        <span>Страна:</span>
                                        <span id="js_country_select_wrap"></span>

                                        <?= $this->getHelper(Form::class)->getFieldError(
                                            $this->getErrors()->get('country')
                                        ) ?>
                                    </p>
                                    <p>
                                        <span>Регион:</span>
                                        <span id="js_region_select_wrap"></span>

                                        <?= $this->getHelper(Form::class)->getFieldError(
                                            $this->getErrors()->get('region')
                                        ) ?>
                                    </p>
                                    <p>
                                        <span>Город:</span>
                                        <span id="js_city_select_wrap"></span>

                                        <?= $this->getHelper(Form::class)->getFieldError(
                                            $this->getErrors()->get('city')
                                        ) ?>
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div class="field_row">
                            <label class="compulsory">
                                Тип вашего аккаунта:
                            </label>
                            <div class="group radiobuttons_classic">
                                <?= $this->getHelper(Form::class)->inputHidden(
                                    'advert[user_type]',
                                    '',
                                    ['id' => 'user_type']
                                )->getHtml() ?>
                                <?php foreach (UserType::TYPES as $type => $value): ?><?=
                                    $this->getHelper(Form::class)->inputRadio(
                                        'user[user_type]',
                                        $type,
                                        $user->getType()->getValue(),
                                        [
                                            'id' => 'user_type_' . $type
                                        ]
                                    )->getHtml() ?><?=
                                    $this->getHelper(Form::class)->label(
                                        $value,
                                        'user_type_' . $type
                                    )->getHtml() ?><?php
                                endforeach; ?>

                                <?= $this->getHelper(Form::class)->getFieldError(
                                    $this->getErrors()->get('type')
                                ) ?>
                            </div>
                        </div>

                        <div class="field_row">
                            <label for="user_contact">Дополнительные данные (для компаний).<br>
                                Будут отображаться в каждом вашем объявлении
                                и в вашем <a target="_blank" href="/help/b2b">публичном профиле</a>:</label>
                            <div class="group">
                                <?= $this->getHelper(Form::class)->inputTextArea(
                                    'user[contact]',
                                    $user->getContact(),
                                    [
                                        'id' => 'user_contact'
                                    ]
                                )->getHtml() ?>
                                <div class="animate_field_description">
                                    <div class="animate_field_content">
                                        <div class="description_before_fields">
                                            <p>Если вы собираетесь подавать объявления, например, от лица компании
                                                (юридического лица), укажите в данном поле адрес, график работы
                                                или иную информацию для ваших клиентов.</p>
                                            <p>При подаче каждого нового объявления вам будет дана возможность
                                                указать,
                                                выводить ли данную контактную информацию автоматически в каждом
                                                объявлении или нет.</p>
                                        </div>
                                    </div>
                                    <div class="triangle-right-border"></div>
                                    <div class="triangle-right"></div>
                                </div>

                                <?= $this->getHelper(Form::class)->getFieldError(
                                    $this->getErrors()->get('contact')
                                ) ?>
                            </div>
                        </div>

                        <div class="field_row">
                            <label for="terms_of_service" class="compulsory">
                                Условия использования сайта:
                            </label>
                            <div class="group">
                                <?= $this->getHelper(Form::class)->inputCheckbox(
                                    'terms_of_service',
                                    1,
                                    $this->getRequest()->getRequest('terms_of_service', Request::SANITIZE_INT),
                                    [
                                        'id' => 'terms_of_service',
                                        'required' => 'required'
                                    ]
                                )->getHtml() ?>
                                <label for="terms_of_service">
                                    С <a rel="nofollow" target="_blank" href="/help/terms_of_service/">условиями
                                        использования
                                        сайта</a> ознакомлен(а) и принимаю данные условия.
                                </label>

                                <?= $this->getHelper(Form::class)->getFieldError(
                                    $this->getErrors()->get('terms_of_service')
                                ) ?>
                            </div>
                        </div>

                        <div class="field_row">
                            <label for="terms_of_privacy" class="compulsory">
                                Политика обработки персональных данных:
                            </label>
                            <div class="group">
                                <?= $this->getHelper(Form::class)->inputCheckbox(
                                    'terms_of_privacy',
                                    1,
                                    $this->getRequest()->getRequest('terms_of_privacy', Request::SANITIZE_INT),
                                    [
                                        'id' => 'terms_of_privacy',
                                        'required' => 'required'
                                    ]
                                )->getHtml() ?>
                                <label for="terms_of_privacy">
                                    С <a rel="nofollow" target="_blank" href="/help/privacy">политикой в отношении
                                        обработки персональных данных</a> ознакомлен(а) и принимаю данную политику.
                                </label>

                                <?= $this->getHelper(Form::class)->getFieldError(
                                    $this->getErrors()->get('terms_of_privacy')
                                ) ?>
                            </div>
                        </div>
                    </fieldset>

                    <?= $this->getHelper(Form::class)->inputHidden(
                        $session_name,
                        $session_id
                    )->getHtml() ?>
                    <?= $this->getHelper(Form::class)->inputSubmit(
                        'submit',
                        'Зарегистрироваться',
                        ['class' => 'big_button button_margin_auto']
                    )->getHtml() ?>

                </form>
                <!-- /left -->
            </div>
        </div>
        <div class="right_column">
            <div class="right_column_content">
                <!-- right -->

                <!-- /right -->
            </div>
        </div>
    </article>

</div> <!-- / Content -->

<script>
    document.addEventListener("DOMContentLoaded", function () {
        Krugozor.Location.addCheckedUserLocation(1, '<?= $user->getCountry() ?>');
        Krugozor.Location.addCheckedUserLocation(2, '<?= $user->getRegion() ?>');
        Krugozor.Location.addCheckedUserLocation(3, '<?= $user->getCity() ?>');

        var select_country_attributes = {
            name: 'user[country]',
            value: '<?= $user->getCountry() ?>'
        };
        var selectCountryObj = Krugozor.Location.createLocation(select_country_attributes, 'Выберите страну проживания');
        document.getElementById('js_country_select_wrap').appendChild(selectCountryObj.SelectElement);

        var select_region_attributes = {
            name: 'user[region]',
            value: '<?= $user->getRegion() ?>'
        };
        var selectRegionObj = Krugozor.Location.createLocation(select_region_attributes, 'Выберите регион проживания');
        document.getElementById('js_region_select_wrap').appendChild(selectRegionObj.SelectElement);

        var select_city_attributes = {
            name: 'user[city]',
            value: '<?= $user->getCity() ?>'
        };
        var selectCityObj = Krugozor.Location.createLocation(select_city_attributes, 'Выберите город проживания');
        document.getElementById('js_city_select_wrap').appendChild(selectCityObj.SelectElement);

        selectCountryObj.create(1, 0);
        selectRegionObj.create(2, <?= (int) $user->getCountry() ?>);
        selectCityObj.create(3, <?= (int) $user->getRegion() ?>);
    });
</script>

<?php include $this->getRealTemplatePath('Local/FrontendBottom') ?>
</body>
</html>