<?php

use Krugozor\Framework\View;

/* @var $this View */

?>
<!DOCTYPE html>
<html lang="ru">
<head>

    <?php include($this->getRealTemplatePath('Local/MetaTags')); ?>

    <?= $this->compileCss([
        'local' => ['reset.css', 'tags.css', 'classes.css', 'structure.css'],
        'not-found' => ['not-found.css']
    ]) ?>

</head>
<body>

<?php include $this->getRealTemplatePath('Local/FrontendTop') ?>

<div id="<?= $this->getPageId() ?>" class="content">

    <?php include $this->getRealTemplatePath('Common/Notification') ?>

    <header><h1>Доступ запрещён</h1></header>

    <div class="header_big center">403</div>
    <div class="header_medium center">Forbidden</div>

    <p class="not_found_description">Запрошенный документ запрещён для показа.
        Вы можете <a href="/advert/frontend-edit-advert/">подать объявление</a>,
        войти в <a href="/authorization/frontend-login/">личный кабинет</a> или
        перейти на <a href="/">главную страницу</a> сайта.</p>
</div>

<?php require_once $this->getRealTemplatePath('Local/FrontendBottom'); ?>

</body>
</html>